version: "3"

services:
  nginx:
    image: nginx:1.15.11
    container_name: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    command: /bin/bash -c "nginx -g 'daemon off;'"
    ports:
      - "443:443"
      - "80:80"
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        registry_external_url 'https://registry.example.com'
        gitlab_rails['registry_enabled'] = true
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 8888
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.example.com.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.example.com.key"
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
      - ./ssl/gitlab.example.com/gitlab.example.com.crt:/etc/gitlab/ssl/gitlab.example.com.crt:ro
      - ./ssl/gitlab.example.com/gitlab.example.com.key:/etc/gitlab/ssl/gitlab.example.com.key:ro
    ports:
      - "22:22"
    restart: always

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - ./ssl/gitlab.example.com/gitlab.example.com.crt:/etc/gitlab-runner/certs/ca.crt:ro
      - ./ssl/gitlab.example.com/gitlab.example.com.crt:/etc/ssl/certs/ca-certificates.crt:ro
    links:
      - nginx:gitlab.example.com
    restart: always

  registry:
    image: registry:2
    container_name: registry
    restart: always

  hello-world:
    image: registry.example.com/test/react
    build: .
