version: "3"

services:
  registry:
    image: registry:2
    restart: always

  nginx:
    image: nginx:1.15.11
    container_name: nginx
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "443:443"
    restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        nginx['listen_https'] = false
        nginx['listen_port'] = 80
        registry_external_url 'https://registry.example.com'
        gitlab_rails['registry_enabled'] = true
        registry_nginx['listen_https'] = false
        registry_nginx['listen_port'] = 8888
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    ports:
      - "22:22"
    restart: always
  hello-world:
    image: registry.example.com/test/react
    build: .
