version: "3"

services:
  # registry:
  #   image: registry:2
  #   container_name: registry
  #   restart: always

  # nginx:
  #   image: nginx:1.15.11
  #   container_name: nginx
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl
  #   command: /bin/bash -c "nginx -g 'daemon off;'"
  #   ports:
  #     - "443:443"
  #     - "80:80"
  #     - "22:22"
  #   restart: always

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    hostname: gitlab.example.com
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    volumes:
      - /srv/gitlab/config:/etc/gitlab
      - /srv/gitlab/logs:/var/log/gitlab
      - /srv/gitlab/data:/var/opt/gitlab
    ports:
      - "80:80"
      - "22:22"
      - "443:443"
    restart: always

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    environment:
      - CI_SERVER_URL=https://gitlab.example.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/gitlab-runner/config:/etc/gitlab-runner
      - ./gitlab-ssl:/ssl
    links:
      - gitlab:gitlab.example.com
    restart: always
  # hello-world:
  #   image: registry.example.com/test/react
  #   build: .
